### ISSUE TITLE
Option to enable listening for switch-master events and disabeling polling interval.

### ISSUE THREAD

**Issue by archef2000** [patrickdk77/redis-sentinel-proxy#3]
Would you accept a PR for such a feature and how would you like to configure this option? As a repalcement option or increase the interval between polling? Or have the `CHECKMS` option be able to turn off the polling by setting it to 0?

**Comment by patrickdk77** [comment]
not sure why I didn't receive a notice of this, but.
setting CHECKMS to 0 would be my method, as to not break existing pulling in a new image to existing configs

**Comment by archef2000** [comment]
I already implemented it, but it has a lot of code changes as I decided that that a toggle would be the best as to have a selt healing way if a change would be missed and just run an extra pull every 30 min or configured by the CHECKMS option. Also the event listener option pulls the current master just bevor it starts listenting so it a sentinel would stop and the master would chenge right at that moment (both on the same node) it could miss the master change.

I am currently testing it.

**Comment by archef2000** [comment]
I created a fork at https://github.com/archef2000/redis-sentinel-proxy have a look. I ran it for some time on my server and github shows the diff very bad as many things like debug and authentication were moved into functions for both pulling and listenting.

**Comment by archef2000** [comment]
Would you accept a PR or is it too much of a change?
